fix:[DOCS] Add proper README
Kendall-Does-Coding-Websites/free-hosting-via-pr pull request #10
Opened 2022-06-30 01:40 UTC by Pericles001

resolves #7

2022-06-30 07:47 UTC, KendallDoesCoding requested changes

2022-06-30 07:47 UTC, KendallDoesCoding commented on README.md
> +## Aknowledgements
```suggestion
## Acnowledgements
```

fix typo

2022-06-30 07:47 UTC, KendallDoesCoding commented on README.md
> +...
KendallDoesCoding - built software
Netlify - using their software.

2022-06-30 07:48 UTC, KendallDoesCoding commented on README.md
> +...
@Pericles001 Please add the needful and will merge.

2022-06-30 13:22 UTC, Pericles001 commented on README.md
> +...
I will do that soon. Thanks for reviewing.

2022-06-30 14:49 UTC, KendallDoesCoding commented on README.md
> +...
Thanks!

2022-06-30 23:49 UTC, Pericles001 commented on README.md
> +...
It is done.

2022-07-01 08:01 UTC, KendallDoesCoding approved these changes
LGTM ✔️

2022-07-01 08:01 UTC, KendallDoesCoding commented
Thanks for your contribution! Merging.

2022-07-01 08:02 UTC, merged

2022-07-01 08:02 UTC, KendallDoesCoding commented
Thanks for your contribution! Merging.

2022-07-01 12:12 UTC, Pericles001 commented
> Thanks for your contribution! Merging.

You're welcome!